language: bash
sudo: false

env:
  global:
    - PATH=/usr/bin:/bin:./:/usr/local/bin

install:
  - export GIT_COMMIT="$(curl -v -s -f "https://api.github.com/repos/tincantech/easyrsa-unit-tests/git/refs/heads/master" | sed -e "s\`,\`\n\`g" -e "s\`\"\`\`g" | grep 'sha:' | awk '{print $2}')"

#before_script:
#  - export GIT_COMMIT="$(curl -v -s -f "https://api.github.com/repos/tincantech/easyrsa-unit-tests/git/refs/heads/master" | sed -e "s\`,\`\n\`g" -e "s\`\"\`\`g" | grep 'sha:' | awk '{print $2}')"

matrix:
  include:
    - os: linux
      dist: bionic
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - sh op_test.sh
