language: bash
sudo: false

# Large File Storage .. probably not what i want.
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

matrix:
  allow_failures:
  include:
    - os: linux
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - sh op_test.sh

