language: bash
sudo: false

install:
  - GIT_HEAD="$(curl -v -s -f "https://api.github.com/repos/tincantech/easyrsa-unit-tests/git/refs/heads/master" | sed -e "s\`,\`\n\`g" -e "s\`\"\`\`g" | grep 'sha:' | awk '{print $2}')"; echo "GIT_HEAD: $GIT_HEAD"

matrix:
  include:
    - os: linux
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - op_test.sh

